<?php

namespace SportFunBundle\Entity;

/**
 * StadiumTennisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadiumTennisRepository extends \Doctrine\ORM\EntityRepository
{
}
