<?php

namespace SportFunBundle\Entity;

/**
 * StadiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadiumRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAroundSuburb($suburb){
        $qb = $this->createQueryBuilder("s")
            ->where("s.suburb = :suburb")
        ->setParameter('suburb', $suburb)
        ->getQuery();

        return $qb->getResult();
    }

    public function updateMapType($id, $type) {
        $connection = $this->getEntityManager()->getConnection();
        $sql = "UPDATE stadium
                SET stadium.maptype = :type
                WHERE id = :id";
        $stmt = $connection->prepare($sql);
        $stmt->bindValue('type' , $type);
        $stmt->bindValue('id', $id);
        $stmt->execute();
    }
}
