<?php

namespace SportFunBundle\Entity;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllStates(){
        $qb = $this->createQueryBuilder("s")
            ->orderBy('name');
        return $qb;
    }

}
