<?php

namespace SportFunBundle\Entity;

/**
 * TennisCourtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TennisCourtRepository extends \Doctrine\ORM\EntityRepository
{
}
